version: '3'

services:

  notebook:
    build: notebook/
    container_name: notebook
    ports:
      - "8888:8888"
    depends_on:
      - elasticsearch
    volumes:
      - ./indexer/:/home/jovyan/work/
    environment:
      - JUPYTER_TOKEN=admin 

  elasticsearch:
    build: elasticsearch/
    ports:
      - 9200:9200
      - 9300:9300
    container_name: elasticsearch

  # indexer:
  #   build: indexer/
  #   depends_on:
  #     - elasticsearch
  #   container_name: indexer

  kibana:
    build: kibana/
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    container_name: kibana
  